# Generated by Django 5.1.2 on 2025-02-17 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('host', 'Host'), ('renter', 'Renter')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='available', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveIntegerField()),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('furnished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('is_inappropriate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.users')),
            ],
        ),
    ]
