# Generated by Django 5.1.2 on 2025-02-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='properties',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
